---
- name: Install HTTPD Service
  hosts: ansible2.example.com
  vars:
    web_package: httpd
    fw_package: firewalld
    web_service: httpd
    fw_service: firewalld
    rule: http

  tasks:
    - name: Require packages installed to be up to date
      yum:
        name:
          - "{{ web_package }}"
          - "{{ fw_package }}"
        state: latest

    - name: The {{ fw_service }} service is started and enabled
      service:
        name: "{{ fw_service }}"
        enabled: true
        state: started

    - name: The {{ web_service }} service is started and enabled
      service:
        name: "{{ web_service }}"
        enabled: true
        state: started

    - name: Insert Web Content
      copy:
        content: "Welcome to RL Web Site!"
        dest: /var/www/html/index.html

    - name: The firewall port for {{ rule }} is open
      firewalld:
        service: "{{ rule }}"
        permanent: true
        immediate: true
        state: enabled

- name: Verify Web Page
  hosts: localhost
  become: false
  tasks:
    - name: Ensure the webserver is reachable
      uri:
        url: http://ansible2.example.com
        status_code: 200
